brew cask install amethyst
brew cask install appcleaner
brew cask install battery-guardian
brew cask install caffeine
brew cask install cord
brew cask install dropbox
brew cask install evernote
brew cask install google-chrome
brew cask install opera
#brew cask install opera-developer
brew cask install slack
brew cask install hipchat
brew cask install skype
brew cask install iterm2

brew cask install limechat
brew cask install mou
brew cask install quicklook-json
brew cask install rescuetime
brew cask install sequel-pro
brew cask install spotify

brew cask install the-unarchiver
brew cask install transmit
brew cask install transmission
#brew cask install vagrant
#brew cask install virtualbox
brew cask install vlc
brew cask install postman
brew cask install sourcetree
brew cask install robomongo
brew cask install rdm
