display_full_path = false
excluded_dirs = [
    ".git",
    "node_modules",
    ".cache",
    ".Trash",
    "Library",
    "Downloads",
    "Desktop",
    "Movies",
    "Music",
    "Pictures",
    "Public",
    "Applications",
    ".npm",
    ".pnpm-store",
    ".bun",
    ".cargo",
    ".rustup",
]
bookmarks = ["/Users/ivanpereira/work/src/polly/polly"]

[[search_dirs]]
path = "~"
depth = 4
